baseURL = "https://timosarkar.netlify.app"
languageCode = "en-us"
title = "Timo Sarkar"
theme = "hugo-natrium-theme"

publishDir = "dist"
relativeURLs = true
canonifyURLs = true
disqusShortname = 'timosarkar'

preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
pygmentsCodefences = true
pygmentsStyle = "native"

# https://gohugohq.com/partials/emojis-shortcode-for-hugo/
enableEmoji = true
# [blackfriday]
#     enableEmoji = true

# Possible Options for math (put these in the front matter)
# markup = "markdown"
# katex = false

[taxonomies]
category = "categories"
tag = "tags"

[permalinks]
post = "/:slug/"
page = "/:slug/"

[[menu.main]]
name = "About"
url = "/about/"
weight = -110

[[menu.main]]
name = "Tags"
url = "/tags"
weight = -120

[[menu.main]]
name = "Categories"
url = "/categories"
weight = -130

[params]
description = ""

[params.logo]
url = "logo.png"
width = 50
height = 50
alt = "Logo"
